test(deps): udpate webdriver binaries to 3.2
* Update `webdriver-binaries` gradle plugin to 3.2
* Fixes #184 `java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasTouchScreen` by forcing seleniumVersion. This is due to conflict in the selenium libraries.